services:
  wb-ansible:           # 指定服务名称
    build: ./django    #指定Dockerfile所在路径
    volumes:                  # 挂载目录
      - ../../wb-ansible/:/app
    environment:                     #定义环境变量
      - TZ=Asia/Shanghai             #指定时区
    
    ports:                          # 指定端口映射
     - "8000:8000"
     
  celery-worker:   # 指定服务名称
    build: ./worker    #指定 Dockerfile所在路径
    volumes:                  # 挂载目录
      - ../../wb-ansible/:/app
    environment:
      - TZ=Asia/Shanghai
  redis:
    image: "redis:latest"
    ports:                          # 指定端口映射
     - "6379:6379"