# Generated by Django 5.2.4 on 2025-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': 'Celery任务记录',
                'verbose_name_plural': 'Celery任务记录',
            },
        ),
    ]
