# Generated by Django 5.2.4 on 2025-07-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_run', '0001_initial'),
        ('runner_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='celery_tasks', to='runner_jobs.job', verbose_name='所属任务'),
            preserve_default=False,
        ),
    ]
