# Generated by Django 5.2.4 on 2025-07-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_run', '0003_alter_celerytask_job'),
        ('runner_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celery_tasks', to='runner_jobs.job', verbose_name='所属任务'),
        ),
    ]
