# Generated by Django 5.2.4 on 2025-07-24 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_run', '0004_celerytask_job_name_celerytask_job_type_and_more'),
        ('runner_jobs', '0002_job_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='job_type',
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='celery_tasks', to='runner_jobs.job', verbose_name='所属任务'),
            preserve_default=False,
        ),
    ]
