FROM python:3.11
 
# 设置工作目录
WORKDIR /app
 
# 复制要求的依赖文件到容器内
COPY requirements.txt /app/
# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple 

RUN apt-get update && apt-get install sshpass 

CMD ["celery", "-A", "mycelery.main", "worker", "--loglevel=info", "-c" ,"10"]
