# Generated by Django 5.0.3 on 2025-07-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'username')},
        ),
    ]
