# Generated by Django 5.2.4 on 2025-07-24 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_manager', '0001_initial'),
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('job_type', models.CharField(choices=[('playbook', 'Playbook'), ('adhoc', 'Ad-Hoc 命令'), ('script', 'shell脚本')], max_length=10, verbose_name='任务类型')),
                ('module_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='模块名（如 shell/command）')),
                ('module_args', models.CharField(blank=True, max_length=512, null=True, verbose_name='模块参数')),
                ('extra_vars', models.TextField(blank=True, null=True, verbose_name='额外变量（JSON格式）')),
                ('forks', models.PositiveIntegerField(default=5, verbose_name='并发数')),
                ('verbosity', models.PositiveIntegerField(default=0, verbose_name='日志详细程度（0~5）')),
                ('playbook_content', models.TextField(blank=True, null=True, verbose_name='Playbook 内容（YAML）')),
                ('playbook_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Playbook 文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ManyToManyField(to='host_manager.host', verbose_name='目标主机')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scripts.script', verbose_name='关联的 Playbook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Ansible 任务',
                'verbose_name_plural': 'Ansible 任务列表',
            },
        ),
    ]
