# Generated by Django 5.2.4 on 2025-07-10 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('job_type', models.CharField(choices=[('playbook', 'Playbook'), ('adhoc', 'Ad-Hoc 命令')], max_length=10, verbose_name='任务类型')),
                ('inventory', models.TextField(verbose_name='目标主机列表（JSON格式）')),
                ('playbook_content', models.TextField(blank=True, null=True, verbose_name='Playbook 内容（YAML）')),
                ('playbook_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Playbook 文件路径')),
                ('module_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='模块名（如 shell/command）')),
                ('module_args', models.CharField(blank=True, max_length=512, null=True, verbose_name='模块参数')),
                ('extra_vars', models.TextField(blank=True, null=True, verbose_name='额外变量（JSON格式）')),
                ('forks', models.PositiveIntegerField(default=5, verbose_name='并发数')),
                ('verbosity', models.PositiveIntegerField(default=0, verbose_name='日志详细程度（0~5）')),
            ],
            options={
                'verbose_name': 'Ansible 任务',
                'verbose_name_plural': 'Ansible 任务列表',
            },
        ),
    ]
