# Generated by Django 5.2.4 on 2025-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
    ]
