# Generated by Django 5.2.4 on 2025-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0001_initial'),
        ('runner_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='host_manager.host', verbose_name='目标主机'),
        ),
    ]
