# Generated by Django 5.2.4 on 2025-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0002_host_users'),
        ('runner_jobs', '0003_job_created_at_job_playbook_job_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='inventory',
        ),
        migrations.AddField(
            model_name='job',
            name='inventory',
            field=models.ManyToManyField(to='host_manager.host', verbose_name='目标主机'),
        ),
    ]
