# Generated by Django 5.2.4 on 2025-07-22 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('ssh_password_encrypted', models.BinaryField(blank=True, null=True, verbose_name='加密后的SSH密码')),
                ('become_password_encrypted', models.BinaryField(blank=True, null=True, verbose_name='加密后的提权密码')),
                ('users', models.ManyToManyField(blank=True, related_name='hosts', to=settings.AUTH_USER_MODEL, verbose_name='可用该主机的用户')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'host',
            },
        ),
    ]
