# Generated by Django 5.2.4 on 2025-07-14 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='hosts', to=settings.AUTH_USER_MODEL, verbose_name='可用该主机的用户'),
        ),
    ]
