# Generated by Django 5.2.4 on 2025-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0002_host_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='become_password_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='加密后的提权密码'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_password_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='加密后的SSH密码'),
        ),
    ]
